### ISSUE TITLE
Problems with parallel checkouts: Outdated cart objects

### ISSUE THREAD

**Issue by EinShoppo** [coreshop/CoreShop#2245]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Hello there,

we have some problems with parallel checkouts in CoreShop 3: As soon as we make (almost) simultaneously checkouts with two or more visitors (via WAPT Pro load testing tool), we get the following errors in some cases:

**Address Checkout Step:**
/src/Checkout/Step/AddressCheckoutStep.php:78: "Customer not set" exception.

Actually the cart object has a Customer but its cache entry (Pimcore Cache) is outdated, so in the cached object we have no Customer yet. Only after deleting the cache entry from redis, we can see up to date data within Pimcore admin backend.

**Summary Checkout Step:**
The visitor is redirected back to payment step because its validation fails. This is probably a similar mistake, it looks likes the PaymentProvider is not set within the (cached) cart used in summary step. The payment step's validation was successful before, since we were able to reach the summary step...

We tried to clear the cart's cache before saving the cart in \CoreShop\Manager\CartManager in Line 87 to get a brandnew cache entry. Unfortunately, it doesn't help.

Do you know about problems with parallel checkouts or have any ideas for a solution?

Best regards!

**Comment by dpfaffenbauer** [comment]
@EinShoppo what redis setup do you use? We never experienced this kind of issues. it also sounds more like a Pimcore issue too. Since cache items aren't up2date.

**Comment by EinShoppo** [comment]
@dpfaffenbauer  We have two redis containers, one for session and one for cache. Version 6.2.10.

Nothing special, as far as I see.

**Comment by dpfaffenbauer** [comment]
I don't see what we could approve here. Pimcore always stores the DataObjects in cache....

**Comment by EinShoppo** [comment]
Hi @dpfaffenbauer,
we made some parallel checkouts against your demo shop. Don't worry, just a few, no real stress test. 

With five parallel users within the shop we got 15 failed sessions and only seven sucessful orders. And we already had problems with two parallel users.

The shop/checkout failed on following requests:
- /en/shop/cart/add/112
- /en/shop/checkout/customer
- /en/shop/checkout/payment
- /en/shop/checkout/address

I really can imagine we have a Pimcore related error here but it seems to be a problem for all (?) Coreshop installations, too. 
We don't have access to your logs, but maybe you can take a look.

**Comment by dpfaffenbauer** [comment]
@EinShoppo interesting. How did you do those tests? 

I cannot see anything in the logs on the demo. The demo gets restarted daily, so if you did that yesterday, the logs are gone. if you did today, it doesn't log.

**Comment by dpfaffenbauer** [comment]
@EinShoppo can you also contact me directly? I think we should look closer into that together.

**Comment by dpfaffenbauer** [comment]
@EinShoppo we've been discussing the issue. we think that the issue might come from when Pimcore actually writes the cache.

1. POST /checkout/payment
2. CoreShop writes the Cart
3. Pimcore writes the cache AFTER the request has been finished
4. GET /checkout/summary reads old cache cause 3 hasn't been finished yet

We're considering always flushing the cache for the cart and the items once the CartManager::persist has been called.

**Comment by EinShoppo** [comment]
@dpfaffenbauer: Yes, we also considered that the cache might be written too late.

However, we have already flushed the cache in CartManager::persist before fetching the data as a test - without success. 

And I could partly see in Redis that the cache still contained outdated data - this shouldn't be the case after the request. But maybe flushing the Cache is executed too late, too?

**Comment by solverat** [comment]
@EinShoppo Thanks for sharing this.

BTW Do you use the recommend redis configuration? I remember that we had some dangerous side effects using redis without the volatile-lru rule.

![image](https://user-images.githubusercontent.com/700119/231210939-1a120d21-bad3-4b0d-a148-08e690278e2f.png)

**Comment by dpfaffenbauer** [comment]
@EinShoppo can you give that a try?

**Comment by dpfaffenbauer** [comment]
@solverat but interestingly, the CoreShop demo does not use redis. it just uses simple and plain pimcore db cache

**Comment by dpfaffenbauer** [comment]
@EinShoppo maybe this helps https://github.com/dpfaffenbauer/CoreShop/commit/7c936189d141d07b4968d1b8b9f11c83aed3b20a

Problem is that Pimcore caches on reads and writes (loaded with listings, getById, save, update). To circumvent that, we just don't allow the cart to be ever cached ever.

**Comment by EinShoppo** [comment]
@dpfaffenbauer @solverat We have a default redis configuration and maxmemory-policy = volatile-lru. 

We have just tested your fix and the result is promising: with 20 parallel users/checkouts we had 80 successful sessions. Many thanks for your help! :-)

However, we still had two errors in the checkout and another one in the addToCart request, but these were "unique constraint violation" db errors. So this seems to me to be a different problem:

Add to cart:
`app.ERROR: PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '/coreshop/carts/2023/04/12/-6436a8f25a95a' for key 'fullpath' in /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117`

Order commit:
`app.ERROR: PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '/coreshop/carts/2023/04/12/-O605' for key 'fullpath' in /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117`

**Comment by dpfaffenbauer** [comment]
@EinShoppo nice :)

Guess next issue comes from concurrency as well. Will see what I can do, for the first issue, I guess we can create a PR for it. @solverat  @dkarlovi Would do you guys think about this?

**Comment by dpfaffenbauer** [comment]
@EinShoppo I think I found the issue: DeadLock. 

The weird thing then comes from how Pimcore handles it. The CoreShop CartManager saves the Cart and the Items in a transaction (https://github.com/coreshop/CoreShop/blob/master/src/CoreShop/Bundle/OrderBundle/Manager/CartManager.php#L55) Reason for that should be quite clear: We don't wanna persist data where its dependants are out-of-date (eg. cart <-> cart item). 

Problem there is, I think, that Pimcore comes into a deadlock on the relations table, therefore rolling back our transaction and never saving the cart, it keeps retrying and eventually will save the cart, but in another transaction, our `transactional` loop doesn't know about it. therefore Pimcore thinks that the Folder for the cart items `/coreshop/carts/[date]/CART_UNIQE_ID` doesn't exist and creates it as a Folder. CoreShop then saves the Cart again and Pimcore fails with Duplicate Path.

This took me hours of debugging, and the only solution I have right now is, to remove our transactional call and deal let Pimcore deal with the Deadlock. WDYT?

**Comment by solverat** [comment]
@dpfaffenbauer i have a dejavu right now. Remember? We had the exact same situation years ago at your office. Beer was involved. But I can't remember the issue (It wasn't about payment entities - for those we also implemented the optimistic lock protection).

However, i even don't know if it ever has been fixed.

**Comment by dpfaffenbauer** [comment]
@solverat I think you mean the issue we had with the versions race-condition? They used to determine the latest version by time, but only used seconds. If you had 2 versions at the same time, you could end up with the wrong latest version.

Deadlocks keep coming all the time: https://github.com/pimcore/pimcore/issues?q=is%3Aissue+deadlock

**Comment by dpfaffenbauer** [comment]
BTW: I've used K6 (https://k6.io/) to test it, great tool for load testing:

```js
import {check, fail, group} from "k6";
import http from "k6/http";

export const options = {
    scenarios: {
        contacts: {
            executor: 'shared-iterations',
            vus: 10,
            iterations: 10,
            maxDuration: '15s'
        },
    },
};

export default function () {
    group("Navigate to Homepage", function () {
        let r = (Math.random() + 1).toString(36).substring(7);
        let response = http.get("https://coreshop-3.localhost/en/shop", {
            headers: {
                accept:
                    "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                "accept-encoding": "gzip, deflate",
                "accept-language": "en-US,en;q=0.9",
                "cache-control": "max-age=0",
                connection: "keep-alive",
                host: "coreshop-3.localhost",
                "upgrade-insecure-requests": "1",
                "x-request-id": r,
                //"cookie": "XDEBUG_SESSION=XDEBUG_ECLIPSE"
            },
        });

        checkStatus({
            response: response,
            expectedStatus: 200,
            failOnError: true,
            printOnError: true
        });

        // extract all of the available products using their "Add to Cart" buttons
        const forms = response
            .html()
            .find("div[class*=product-col]")
            .find('form')
            .toArray();

        const formNames = forms.map(i => {
            return i.get(0).getAttribute("name");
        });

        const formName = formNames[Math.floor(Math.random() * forms.length)];

        response = response.submitForm({
            formSelector: 'form[name="' + formName + '"]',
            params: {
                headers: {
                    "x-request-id": r,
                }
            }
        });

        checkStatus({
            response: response,
            expectedStatus: 200,
            failOnError: true,
            printOnError: true
        });
    });
}

function checkStatus({response, expectedStatus, expectedContent, failOnError, printOnError, dynamicIds}) {
    if (isEmpty(expectedStatus) && isEmpty(expectedContent)) {
        console.warn('No expected status or content specified in call to checkStatus for URL ' + response.url);
        return;
    }

    let contentCheckResult;
    let statusCheckResult;

    let url = response.url;

    if (dynamicIds) {
        dynamicIds.forEach((dynamicId) => {
            if (response.url.includes(dynamicId)) {
                url = url.replace(dynamicId, '[id]');
            }
        });
    }

    if (expectedContent) {
        contentCheckResult = check(response, {
            [`"${expectedContent}" in ${url} response`]: (r) => r.body.includes(expectedContent),
        });
    }

    if (expectedStatus) {
        const obj = {};
        obj[`${response.request.method} ${url} status ${expectedStatus}`] = (r) => r.status === expectedStatus;

        statusCheckResult = check(response, obj);
    }

    if (!statusCheckResult || !contentCheckResult && expectedContent) {
        if (printOnError && response.body) {
            console.log("Unexpected response: " + response.body);
        }
        if (failOnError) {
            if (!statusCheckResult && (!contentCheckResult && expectedContent)) {
                fail(`${response.request.method} ${url} status ${expectedStatus} and "${expectedContent}" not found in response`);
            } else {
                if (!statusCheckResult) {
                    fail(`Received unexpected status code ${response.status} for URL: ${url}, expected ${expectedStatus}`);
                } else if (!contentCheckResult) {
                    fail(`"${expectedContent}" not found in response for URL: ${url}`);
                }
            }
        }
    }
}

function isEmpty(str) {
    return (!str || str.length === 0);
}

```

**Comment by dpfaffenbauer** [comment]
@EinShoppo I think the solution is to get rid of the transactional call in CartManager and let Pimcore deal with the Deadlock. We never really had issues with inconsistency there anyway.

**Comment by EinShoppo** [comment]
@dpfaffenbauer Please excuse the late feedback. 

We have tested the fix and were able to achieve partial success with it:

With 20 parallel users placing orders repeatedly for six minutes, we were able to complete 124 orders. There were no more errors when adding the item to the shopping cart, but 2x the error still occurred when completing the order:

`[2023-04-19T14:25:23.149517+02:00] app.ERROR: PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '/coreshop/carts/2023/04/19/-O1013' for key 'fullpath' in /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117 Stack trace: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(117): PDOStatement->execute() #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1527): Doctrine\DBAL\Driver\PDOStatement->execute() #2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(930): Doctrine\DBAL\Connection->executeStatement() #3 /var/www/html/vendor/pimcore/pimcore/lib/Db/PimcoreExtensionsTrait.php(189): Doctrine\DBAL\Connection->insert() #4 /var/www/html/vendor/pimcore/pimcore/models/DataObject/AbstractObject/Dao.php(78): Pimcore\Db\Connection->insert() #5 /var/www/html/vendor/pimcore/pimcore/models/DataObject/AbstractObject.php(754): Pimcore\Model\DataObject\AbstractObject\Dao->create() #6 /var/www/html/vendor/pimcore/pimcore/models/Element/Service.php(1027): Pimcore\Model\DataObject\AbstractObject->save() #7 /var/www/html/vendor/coreshop/core-shop/src/CoreShop/Component/Pimcore/DataObject/ObjectService.php(35): Pimcore\Model\Element\Service::createFolderByPath() #8 /var/www/html/vendor/coreshop/core-shop/src/CoreShop/Component/Resource/Service/FolderCreationService.php(75): CoreShop\Component\Pimcore\DataObject\ObjectService->createFolderByPath() #9 /var/www/html/vendor/coreshop/core-shop/src/CoreShop/Bundle/OrderBundle/Manager/CartManager.php(66): CoreShop\Component\Resource\Service\FolderCreationService->createFolderForResource() #10 /var/www/html/vendor/coreshop/core-shop/src/CoreShop/Component/Pimcore/DataObject/VersionHelper.php(43): CoreShop\Bundle\OrderBundle\Manager\CartManager->CoreShop\Bundle\OrderBundle\Manager\{closure}() #11 /var/www/html/vendor/coreshop/core-shop/src/CoreShop/Bundle/OrderBundle/Manager/CartManager.php(85): CoreShop\Component\Pimcore\DataObject\VersionHelper::useVersioning() #12 /var/www/html/vendor/coreshop/core-shop/src/CoreShop/Component/Core/Order/Committer/OrderCommitter.php(78): CoreShop\Bundle\OrderBundle\Manager\CartManager->persistCart() #13 [internal function]: CoreShop\Component\Core\Order\Committer\OrderCommitter->commitOrder() ...`

We also noticed that the add-to-cart error still occurs every time directly after a deployment, but not at all afterwards after the fix. Since we did a manual order before the stress test, which then triggered this initial error case, this one error is not listed above.

By the way, we are still running on Coreshop 3.0.3, so I adjusted the patch accordingly so that it could be applied.

Thanks for the fix, it has already provided another improvement.

Best regards

Translated with www.DeepL.com/Translator (free version)

**Comment by dpfaffenbauer** [comment]
@EinShoppo I've done some further debugging and found that the issue comes from 2 follow up issues:

The Parent Child relation of a Order and a OrderItem. The OrderItems currently are under [order]/items. When the order gets commited, it gets moved to /coreshop/orders/[DATE]/. Pimcore then moves the items "sort of" first and creates a folder for it. but then coreshop moves the order and it gets the unique constraint issue. Solution: Change the folder structure
```
 - coreshop
   - cart
     -  [token]
        - order-object
        - items-folder
```

so the moving of the order doesn't affect the items.

2nd issue: Deadlock :D, again. CoreShop stores notes for the history of whats happening with the order, and in a high load environment, the notes_data table deadlocks. Solution: Either add these notes async with messenger, or introduce deadlock handling in CoreShop for that.

I've pushed the changes into this branch https://github.com/dpfaffenbauer/CoreShop/tree/issues/2245. I managed to have 10 virtual users for a time of 2 minutes with a total of 130 Orders without any issue.

**Comment by dpfaffenbauer** [comment]
I found another solution: Locking the Sequence Table also solves it.

**Comment by dpfaffenbauer** [comment]
this is also needed for it to work properly on high concurrency: https://github.com/pimcore/pimcore/pull/15068

**Comment by dpfaffenbauer** [comment]
@EinShoppo all findings are part of the 3.0.5 release. From my point of view, it works much better now. Can you give some feedback as well?

**Comment by EinShoppo** [comment]
Please excuse the late feedback. We had some tests with a patched CoreShop 3.0.3 version. The results were still promising, even though we found a few bugs - but others.
I think we will upgrade to the latest CoreShop 3.0.5. version shortly, then we will run tests again. We will also keep an eye on [pimcore/pimcore#15068](https://github.com/pimcore/pimcore/pull/15068).

Thanks again for your support! I think the performance/stability in the checkout has taken a big step forward with this bugfix. :-)

**Comment by dpfaffenbauer** [comment]
@EinShoppo Pimcore PR has been merged
